version: '3'
services:
  web:
    container_name: php-book-app-web
    build:
      context: .
<<<<<<< HEAD
      dockerfile: ./Docker/php/Dockerfile
=======
      dockerfile: ./Dockerfile
>>>>>>> origin/master
    volumes:
      - .:/var/www/html:cached
    environment:
      - APP_DEFAULT_LOCALE=ja_JP
      - APP_DEFAULT_TIMEZONE=Asia/Tokyo
      - DATABASE_HOST=php-book-app-db
      - DATABASE_USER=root
      - DATABASE_PASS=secret
<<<<<<< HEAD
      - DATABASE_NAME=sakaedb
=======
      - DATABASE_NAME=qa_app
>>>>>>> origin/master
    ports:
      - "5000:80"
  db:
    container_name: php-book-app-db
    build:
      context: .
<<<<<<< HEAD
      dockerfile: ./Docker/mysql/Dockerfile
=======
      dockerfile: ./Dockerfile
>>>>>>> origin/master
    volumes:
      - ./Docker/mysql/sqls:/docker-entrypoint-initdb.d
      - ./Docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "13306:3306"